### ISSUE TITLE
node_modules package.json issue

### ISSUE THREAD

**Issue by Leigh-M** [NaturalIntelligence/detailed-xml-validator#4]
(This module if running would be extremely useful as there are issues with all of the others on npm performing XML validation against a given XSD  - if there is a donate page to encourage it's development please post it somewhere happy to donate)

However, running into a require issue (node 14.15.0  npm v 8.3.0  Ubuntu Linux 21.10) right at the outset - the npm packaging does not look to be set up correctly:

After `npm i detailed-xml-validator`

I see:

`Error: Cannot find module '/home/my-home/projects/some-project/node_modules/detailed-xml-validator/validator.js'. Please verify that the package.json has a valid "main" entry`

package.json has a main entry, but appears to point to: validator.js  -  you can get this to run correctly (I think) by changing that to:  `"main": "./src/validator.js"`

**Comment by amitguptagwl** [comment]
Thanks for highlighting this. Fixed and published the changes.
