### ISSUE TITLE
Not validating against a given XSD schema

### ISSUE THREAD

**Issue by Leigh-M** [NaturalIntelligence/detailed-xml-validator#5]
The module appears to just verify if the XML file is valid XML, I can pass in an XSD schema which it accepts, eg:

`<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.1">
	<xs:element name="job-opportunities">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="job-opportunity" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="isMigration" type="shortTextInputType"/>
			<xs:attribute name="isIncremental" type="xs:boolean" default="false"/>
			<xs:attribute name="datasourceKey" type="shortTextInputType"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="job-opportunity">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="job-id" type="textInputID" minOccurs="1" maxOccurs="1"/>
  ...
`

And if I remove for eg 'job-id' from one of the input objects (XML fields) then it should fail validation - however it passes validation

**Comment by amitguptagwl** [comment]
This module uses it's own rule file which is different than XSD and looks more like XML data file. More features would be added in future versions. Currently, it just ensures frequency, type, range, and null validations only on top of syntax check done by FXP.
