### ISSUE TITLE
It is validating against rules but not syntax. 

### ISSUE THREAD

**Issue by gautam-jha** [NaturalIntelligence/detailed-xml-validator#6]
Hello,
I am using this in a project and noticed that it is validating against rules written only when XML is valid but considering reallife scenarios people make syntax error. but in that case it is returning undefined.

**Comment by amitguptagwl** [comment]
@gautam-jha can you please share the sample code? In which scenario you feel error is not being thrown.

```js
    it("Syntax error in rules XML data", async function(){
        assert.throws(() => {
            new Validator(errData);
        }, "Attribute '<name' is an invalid name.:9");
    });
```

**Comment by amitguptagwl** [comment]
Closing as an old issue. Please reopen is you still find this issue.
